### ISSUE TITLE
Who oversaw the construction of the Clifton Suspension bridge ?

### ISSUE THREAD

**Issue by drslock** [pose-uob/POSE2022#4]

**Comment by tfabes** [comment]
The bridge was initially designed by Isambard Kingdom Brunel, with further revisions being carried out on the plans by William Barlow and John Hawkshaw. Construction of the bridge was interrupted by the 1831 Bristol Riots, the contractors going bankrupt in 1837, and Brunel's death in 1859. The chains were purchased in 1860 from the Hungerford suspension bridge in London. The bridge was not completed until 1864. The primary people who are accredited with overseeing the construction are Barlow and Hawkshaw, however this is often misattributed to Brunel. In a more hands-on sense, Thomas Evans was the onsite manager for the 1830's to the early 1840's.
